name: Go tests

# Run pretty much all the time
on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: golang:alpine

    env:
      # Disable CGO to avoid errors due to using alpine contianer
      CGO_ENABLED: "0"

    steps:

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get dependencies
        run:  go get -v -t -d ./...

      # Check that the packages can be built:
      #
      # > When compiling multiple packages or a single non-main package,
      # > build compiles the packages but discards the resulting object,
      # > serving only as a check that the packages can be built.
      - name: Build
        run: go build -v ./...

      # Run all tests.
      - name: Test
        run: go test -v ./...